spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wlc
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  secret: worklifechallengeprojecttokensecretkey01234567891011121314151617181920
  expiration_time: 3600000
  pre_fix: Bearer